fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: no_reply@xxx.com
        sender_name: xxx
    group:
        group_class: App\Entity\Group