fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: AppBundle\Entity\User
  from_email:
    address: "xxxxx@gmail.com"
    sender_name: "xxxxx@gmail.com"
  registration:
    form:
      type: App\Form\RegistrationType
      # if you are using Symfony < 2.8 you should use the type name instead
      # type: app_user_registration
  doctrine:
    orm:
      auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: false
        mappings:
          FOSUserBundle: ~
          UserQuestRepository:
            type: annotation
            dir: %kernel.root_dir%/../src/Repository/UserQuestRepository
            prefix: App\Repository\UserQuestRepository
  nelmio_cors:
    defaults:
      allow_origin: ['%cors_allow_origin%']
      allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
      allow_headers: ['content-type', 'authorization']
      expose_headers: ['link']
      max_age: 3600
    paths:
      '^/': ~